/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_demo_MonteCarloMapper */

#ifndef _Included_com_intel_demo_MonteCarloMapper
#define _Included_com_intel_demo_MonteCarloMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_demo_MonteCarloMapper
 * Method:    monteCarlo
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_intel_demo_MonteCarloMapper_monteCarlo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
