/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MonteCarloDemo */

#ifndef _Included_MonteCarloDemo
#define _Included_MonteCarloDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MonteCarloDemo
 * Method:    nativeMonteCarlo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MonteCarloDemo_nativeMonteCarlo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
